### ISSUE TITLE
[Suggestion] заскидьте oresim с meteor rejects?

### ISSUE THREAD

**Issue by erxson** [TheBreakery/Bloomware#5]
вроде идея хайповая

**Comment by OffeeX** [comment]
а че шо? я просто не користуюсь аддонами на метеор

**Comment by erxson** [comment]
Чтобы по сиду видить руды. Типо, ты узнаешь сид мира и с помощью oresim обходишь антииксрей. В орсиме есть еще поддержка баритона, так шо вообще имбуля
