### ISSUE TITLE
Add Kotlin pls

### ISSUE THREAD

**Issue by The-Forecaster** [TheBreakery/Bloomware#69]
**Explain what you want to be added**
Add the kotlin coding language to this project

**Describe the solution you'd like**
Add it in the build.gradle file.
If would also like to see coroutines added but just having kotlin in general is good

**Describe alternatives you've considered**
Java is stinky i dont wanna use java

**Additional context**
:D

**Comment by OffeeX** [comment]
Use a lombok. Lombok + java > kotlin

**Comment by cattyngmd** [comment]
> **Describe alternatives you've considered** Java is stinky i dont wanna use java

No. You're stinky
